// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/terra-project/core/x/wasm/internal/types/
// ALIASGEN: github.com/terra-project/core/x/wasm/internal/keeper/
package wasm

import (
	"github.com/terra-project/core/x/wasm/internal/keeper"
	"github.com/terra-project/core/x/wasm/internal/types"
)

const (
	DefaultCodespace      = types.DefaultCodespace
	CodeCreatedFailed     = types.CodeCreatedFailed
	CodeAccountExists     = types.CodeAccountExists
	CodeInstantiateFailed = types.CodeInstantiateFailed
	CodeExecuteFailed     = types.CodeExecuteFailed
	CodeGasLimit          = types.CodeGasLimit
	CodeInvalidGenesis    = types.CodeInvalidGenesis
	CodeNotFound          = types.CodeNotFound
	ModuleName            = types.ModuleName
	StoreKey              = types.StoreKey
	TStoreKey             = types.TStoreKey
	QuerierRoute          = types.QuerierRoute
	RouterKey             = types.RouterKey
	MaxWasmSize           = types.MaxWasmSize
	DefaultParamspace     = types.DefaultParamspace
	QueryGetContractInfo  = types.QueryGetContractInfo
	QueryGetStore         = types.QueryGetStore
	QueryGetMsg           = types.QueryGetMsg
	QueryGetCodeInfo      = types.QueryGetCodeInfo
)

var (
	// functions aliases
	RegisterCodec        = types.RegisterCodec
	NewCodeInfo          = types.NewCodeInfo
	NewWasmAPIParams     = types.NewWasmAPIParams
	NewWasmCoins         = types.NewWasmCoins
	NewContractInfo      = types.NewContractInfo
	ErrCreateFailed      = types.ErrCreateFailed
	ErrAccountExists     = types.ErrAccountExists
	ErrInstantiateFailed = types.ErrInstantiateFailed
	ErrExecuteFailed     = types.ErrExecuteFailed
	ErrGasLimit          = types.ErrGasLimit
	ErrInvalidGenesis    = types.ErrInvalidGenesis
	ErrNotFound          = types.ErrNotFound
	NewGenesisState      = types.NewGenesisState
	DefaultGenesisState  = types.DefaultGenesisState
	ValidateGenesis      = types.ValidateGenesis
	GetCodeInfoKey       = types.GetCodeInfoKey
	GetContractInfoKey   = types.GetContractInfoKey
	GetContractStoreKey  = types.GetContractStoreKey
	DefaultParams        = types.DefaultParams
	NewKeeper            = keeper.NewKeeper
	ParamKeyTable        = keeper.ParamKeyTable
	NewQuerier           = keeper.NewQuerier
	CreateTestInput      = keeper.CreateTestInput

	// variable aliases
	ModuleCdc                    = types.ModuleCdc
	LastCodeIDKey                = types.LastCodeIDKey
	LastInstanceIDKey            = types.LastInstanceIDKey
	CodeKey                      = types.CodeKey
	ContractInfoKey              = types.ContractInfoKey
	ContractStoreKey             = types.ContractStoreKey
	ParamStoreKeyMaxContractSize = types.ParamStoreKeyMaxContractSize
	ParamStoreKeyMaxContractGas  = types.ParamStoreKeyMaxContractGas
	ParamStoreKeyGasMultiplier   = types.ParamStoreKeyGasMultiplier
	DefaultMaxContractSize       = types.DefaultMaxContractSize
	DefaultMaxContractGas        = types.DefaultMaxContractGas
	DefaultGasMultiplier         = types.DefaultGasMultiplier
)

type (
	Model                  = types.Model
	CodeInfo               = types.CodeInfo
	ContractInfo           = types.ContractInfo
	GenesisState           = types.GenesisState
	Code                   = types.Code
	Contract               = types.Contract
	MsgStoreCode           = types.MsgStoreCode
	MsgInstantiateContract = types.MsgInstantiateContract
	MsgExecuteContract     = types.MsgExecuteContract
	Params                 = types.Params
	QueryStoreParams       = types.QueryStoreParams
	QueryMsgParams         = types.QueryMsgParams
	Keeper                 = keeper.Keeper
	InitMsg                = keeper.InitMsg
)
